/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.start;

/**
 *
 * @author astrapi69
 */
public class WizardStartFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lblWelcomeHeader;

	private javax.swing.JLabel lblWelcomeIntro;

	private javax.swing.JRadioButton rbnCreate;


	private javax.swing.JRadioButton rbnImport;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form StartFormPanel
	 */
	public WizardStartFormPanel()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblWelcomeHeader = new javax.swing.JLabel();
		lblWelcomeIntro = new javax.swing.JLabel();
		rbnImport = new javax.swing.JRadioButton();
		rbnCreate = new javax.swing.JRadioButton();

		lblWelcomeHeader.setText("Welcome to the bundle-manager ");

		lblWelcomeIntro.setText(
			"<html>To get started with the bundle-manager Application can choose the following opportunities:");

		rbnImport.setText("Register existing bundle application");

		rbnCreate.setText("<html>Create new bundle application");
		rbnCreate.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				rbnCreateActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(lblWelcomeHeader, javax.swing.GroupLayout.Alignment.LEADING,
							javax.swing.GroupLayout.PREFERRED_SIZE, 380,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblWelcomeIntro, javax.swing.GroupLayout.Alignment.LEADING,
							javax.swing.GroupLayout.PREFERRED_SIZE, 693,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
							layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(rbnImport).addComponent(rbnCreate,
									javax.swing.GroupLayout.PREFERRED_SIZE, 441,
									javax.swing.GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
				.addComponent(lblWelcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(lblWelcomeIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(rbnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(rbnCreate, javax.swing.GroupLayout.PREFERRED_SIZE,
					40, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(97, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void rbnCreateActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_rbnCreateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_rbnCreateActionPerformed
}
