/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.imports;

/**
 *
 * @author astrapi69
 */
public class ImportBundleApplicationStartFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnChooseRootDir;

	private javax.swing.JComboBox<String> cmbDefaultLocale;

	private javax.swing.JLabel lblBundleAppName;

	private javax.swing.JLabel lblChooseRootDir;


	private javax.swing.JLabel lblDefaultLocale;
	private javax.swing.JLabel lblHeaderChooseBundleAppName;
	private javax.swing.JLabel lblSelectedRootDir;
	private javax.swing.JLabel lblWelcomeImportHeader;
	private javax.swing.JTextField txtBundleAppName;
	private javax.swing.JTextField txtSelectedRootDir;
	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form ImportBundleApplicationStartFormPanel
	 */
	public ImportBundleApplicationStartFormPanel()
	{
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblWelcomeImportHeader = new javax.swing.JLabel();
		lblBundleAppName = new javax.swing.JLabel();
		txtBundleAppName = new javax.swing.JTextField();
		lblHeaderChooseBundleAppName = new javax.swing.JLabel();
		btnChooseRootDir = new javax.swing.JButton();
		lblChooseRootDir = new javax.swing.JLabel();
		lblDefaultLocale = new javax.swing.JLabel();
		cmbDefaultLocale = new javax.swing.JComboBox<>();
		lblSelectedRootDir = new javax.swing.JLabel();
		txtSelectedRootDir = new javax.swing.JTextField();

		lblWelcomeImportHeader
			.setText("Import of an existing application with the bundle-manager ");

		lblBundleAppName.setText("Application name");

		txtBundleAppName.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtBundleAppNameActionPerformed(evt);
			}
		});

		lblHeaderChooseBundleAppName.setText("Give your imported bundle-application a name");

		btnChooseRootDir.setText("Choose root directory");

		lblChooseRootDir.setText("Choose the root directory of your project");

		lblDefaultLocale.setText("Choose default locale");

		cmbDefaultLocale.setModel(new javax.swing.DefaultComboBoxModel<>(
			new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblSelectedRootDir.setText("Selected root directory of your project");

		txtSelectedRootDir.setText("None");
		txtSelectedRootDir.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtSelectedRootDirActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(26, 26, 26).addGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblWelcomeImportHeader, javax.swing.GroupLayout.PREFERRED_SIZE,
						473, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap(296, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblHeaderChooseBundleAppName,
						javax.swing.GroupLayout.PREFERRED_SIZE, 395,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGroup(layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(lblSelectedRootDir, javax.swing.GroupLayout.Alignment.LEADING,
							javax.swing.GroupLayout.PREFERRED_SIZE, 309,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
							.addComponent(lblChooseRootDir, javax.swing.GroupLayout.DEFAULT_SIZE,
								309, Short.MAX_VALUE)
							.addComponent(lblDefaultLocale, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
					.addComponent(lblBundleAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 309,
						javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(txtBundleAppName, javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(cmbDefaultLocale, javax.swing.GroupLayout.Alignment.TRAILING,
							0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnChooseRootDir, javax.swing.GroupLayout.Alignment.TRAILING,
							javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
						.addComponent(txtSelectedRootDir,
							javax.swing.GroupLayout.Alignment.TRAILING))
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addContainerGap()
				.addComponent(lblWelcomeImportHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(lblHeaderChooseBundleAppName, javax.swing.GroupLayout.PREFERRED_SIZE,
					30, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblBundleAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(txtBundleAppName, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblDefaultLocale).addComponent(cmbDefaultLocale,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblChooseRootDir, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(btnChooseRootDir))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblSelectedRootDir, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(txtSelectedRootDir, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(31, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents
	private void txtBundleAppNameActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtBundleAppNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtBundleAppNameActionPerformed
	private void txtSelectedRootDirActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtSelectedRootDirActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtSelectedRootDirActionPerformed
}
