/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.astrapi69.bundle.app.panels.start;

/**
 *
 * @author astrapi69
 */
public class StartFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCreate;

	private javax.swing.JButton btnImport;

	private javax.swing.JLabel lblImportOption;


	private javax.swing.JLabel lblNewBundleApp;
	private javax.swing.JLabel lblWelcomeHeader;
	private javax.swing.JLabel lblWelcomeIntro;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form StartFormPanel
	 */
	public StartFormPanel()
	{
		initComponents();
	}

	private void btnCreateActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnCreateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnCreateActionPerformed

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblWelcomeHeader = new javax.swing.JLabel();
		lblNewBundleApp = new javax.swing.JLabel();
		lblImportOption = new javax.swing.JLabel();
		btnImport = new javax.swing.JButton();
		btnCreate = new javax.swing.JButton();
		lblWelcomeIntro = new javax.swing.JLabel();

		lblWelcomeHeader.setText("Welcome to the bundle-manager ");

		lblNewBundleApp.setText(
			"<html>If you new to the bundle application <br> you have first to create an admin account. Just use the \"Create account\"-Button and follow the steps.");

		lblImportOption.setText(
			"<html>If you have an existing bundle application <br>\nyou can import it. Just use the \"Import\"-Button");

		btnImport.setText("Import");

		btnCreate.setText("Create account");
		btnCreate.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnCreateActionPerformed(evt);
			}
		});

		lblWelcomeIntro.setText(
			"<html>To get started with the bundle-manager Application can choose the following opportunities:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(38, 38, 38).addGroup(layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
						.createSequentialGroup()
						.addComponent(lblWelcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 380,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(313, 313, 313))
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
						false)
						.addComponent(
							lblWelcomeIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 693,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup().addGroup(layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addComponent(lblImportOption, javax.swing.GroupLayout.PREFERRED_SIZE,
								300, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
								javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING,
									javax.swing.GroupLayout.PREFERRED_SIZE, 140,
									javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewBundleApp,
									javax.swing.GroupLayout.Alignment.TRAILING,
									javax.swing.GroupLayout.PREFERRED_SIZE, 300,
									javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap(69, Short.MAX_VALUE)));
		layout
			.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
					.addComponent(lblWelcomeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(lblWelcomeIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(lblImportOption, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblNewBundleApp, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnImport).addComponent(btnCreate))
					.addContainerGap(40, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents
}
