dependencies {

    izpack libs.izpack.ant

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    annotationProcessor libs.spring.boot.configuration.processor
    developmentOnly libs.spring.boot.devtools

    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation libs.observer
    implementation libs.state
    implementation libs.eventbus
    implementation libs.swing.components
    implementation libs.swing.base.components
    implementation libs.swing.tree.component
    implementation libs.swing.splashscreen
    implementation libs.swing.table.components
    implementation libs.menu.actions
    implementation libs.swing.wizard
    implementation libs.json.extensions
    implementation libs.model.data
    implementation libs.resourcebundle.core
    implementation libs.silly.collection
    implementation libs.silly.bean
    implementation libs.jobj.compare
    implementation libs.jobj.core
    implementation libs.file.worker
    implementation libs.bundle.viewmodels
    implementation libs.comparator.extensions
    implementation libs.commons.io
    implementation libs.commons.lang3
    implementation libs.httpclient
    implementation libs.httpmime
    implementation libs.json
    implementation libs.jackson.databind
    implementation libs.guava
    implementation libs.javahelp
    implementation libs.swing.layout
    implementation libs.jxlayer
    implementation libs.swing.worker
    implementation libs.swingx.all
    implementation libs.miglayout.swing
    implementation libs.xml.apis
    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.integration
    implementation libs.spring.boot.starter.validation

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.randomizer
    testImplementation libs.easy.random.core

}
