[versions]
izpack-ant-version = "5.1.3"
lombok-version = "1.18.24"
observer-version = "6"
state-version = "6"
eventbus-version = "6"
swing-components-version = "7.2"
swing-base-components-version = "2.3"
swing-tree-component-version = "2.1"
swing-splashscreen-version = "2"
swing-table-components-version = "2"
menu-actions-version = "2.1"
swing-wizard-version = "2"
json-extensions-version = "2"
model-data-version = "2.1"
resourcebundle-core-version = "5"
silly-collection-version = "20.1"
silly-bean-version = "2"
jobj-compare-version = "11.1"
jobj-core-version = "7"
file-worker-version = "11.4"
bundle-viewmodels-version = "5.6-SNAPSHOT"
comparator-extensions-version = "1.4"
commons-io-version = "2.11.0"
commons-lang3-version = "3.12.0"
httpclient-version = "4.5.13"
httpmime-version = "4.5.13"
json-version = "20220924"
jackson-databind-version = "2.14.0-rc2"
guava-version = "31.1-jre"
javahelp-version = "2.0.05"
swing-layout-version = "1.0.3"
jxlayer-version = "3.0.4"
swing-worker-version = "1.1"
swingx-all-version = "1.6.5-1"
miglayout-swing-version = "11.0"
xml-apis-version = "1.0.b2"
randomizer-version = "8.6"
easy-random-core-version = "5.0.0"
gradle-plugin-grgit-version = "5.2.2"
gradle-plugin-license-version = "0.16.1"
gradle-plugin-lombok-version = "8.6"
gradle-plugin-spotless-version = "7.0.0.BETA1"
gradle-plugin-version-catalog-update-version = "0.8.4"
gradle-plugin-versions-version = "0.51.0"
gradle-izpack-plugin-version = "3.2"

[libraries]
izpack-ant = { module = "org.codehaus.izpack:izpack-ant", version.ref = "izpack-ant-version"}
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version"}
observer = { module = "io.github.astrapi69:observer", version.ref = "observer-version"}
state = { module = "io.github.astrapi69:state", version.ref = "state-version"}
eventbus = { module = "io.github.astrapi69:eventbus", version.ref = "eventbus-version"}
swing-components = { module = "io.github.astrapi69:swing-components", version.ref = "swing-components-version"}
swing-base-components = { module = "io.github.astrapi69:swing-base-components", version.ref = "swing-base-components-version"}
swing-tree-component = { module = "io.github.astrapi69:swing-tree-component", version.ref = "swing-tree-component-version"}
swing-splashscreen = { module = "io.github.astrapi69:swing-splashscreen", version.ref = "swing-splashscreen-version"}
swing-table-components = { module = "io.github.astrapi69:swing-table-components", version.ref = "swing-table-components-version"}
menu-actions = { module = "io.github.astrapi69:menu-actions", version.ref = "menu-actions-version"}
swing-wizard = { module = "io.github.astrapi69:swing-wizard", version.ref = "swing-wizard-version"}
json-extensions = { module = "io.github.astrapi69:json-extensions", version.ref = "json-extensions-version"}
model-data = { module = "io.github.astrapi69:model-data", version.ref = "model-data-version"}
resourcebundle-core = { module = "io.github.astrapi69:resourcebundle-core", version.ref = "resourcebundle-core-version"}
silly-collection = { module = "io.github.astrapi69:silly-collection", version.ref = "silly-collection-version"}
silly-bean = { module = "io.github.astrapi69:silly-bean", version.ref = "silly-bean-version"}
jobj-compare = { module = "io.github.astrapi69:jobj-compare", version.ref = "jobj-compare-version"}
jobj-core = { module = "io.github.astrapi69:jobj-core", version.ref = "jobj-core-version"}
file-worker = { module = "io.github.astrapi69:file-worker", version.ref = "file-worker-version"}
bundle-viewmodels = { module = "io.github.astrapi69:bundle-viewmodels", version.ref = "bundle-viewmodels-version"}
comparator-extensions = { module = "io.github.astrapi69:comparator-extensions", version.ref = "comparator-extensions-version"}
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io-version"}
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3-version"}
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient-version"}
httpmime = { module = "org.apache.httpcomponents:httpmime", version.ref = "httpmime-version"}
json = { module = "org.json:json", version.ref = "json-version"}
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind-version"}
guava = { module = "com.google.guava:guava", version.ref = "guava-version"}
javahelp = { module = "javax.help:javahelp", version.ref = "javahelp-version"}
swing-layout = { module = "org.swinglabs:swing-layout", version.ref = "swing-layout-version"}
jxlayer = { module = "org.swinglabs:jxlayer", version.ref = "jxlayer-version"}
swing-worker = { module = "org.swinglabs:swing-worker", version.ref = "swing-worker-version"}
swingx-all = { module = "org.swinglabs.swingx:swingx-all", version.ref = "swingx-all-version"}
miglayout-swing = { module = "com.miglayout:miglayout-swing", version.ref = "miglayout-swing-version"}
xml-apis = { module = "xml-apis:xml-apis", version.ref = "xml-apis-version"}
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter"}
spring-boot-starter-integration = { module = "org.springframework.boot:spring-boot-starter-integration"}
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation"}
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor"}
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools"}
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test"}
randomizer = { module = "io.github.astrapi69:randomizer", version.ref = "randomizer-version"}
easy-random-core = { module = "org.jeasy:easy-random-core", version.ref = "easy-random-core-version"}

[plugins]
gradle-izpack-plugin = { id = "com.bmuschko.izpack", version.ref = "gradle-izpack-plugin-version" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradle-plugin-versions-version" }
grgit-gradle = { id = "org.ajoberstar.grgit", version.ref = "gradle-plugin-grgit-version" }
license-gradle-plugin = { id = "com.github.hierynomus.license", version.ref = "gradle-plugin-license-version" }
lombok-plugin = { id = "io.freefair.lombok", version.ref = "gradle-plugin-lombok-version" }
spotless-plugin-gradle = { id = "com.diffplug.spotless", version.ref = "gradle-plugin-spotless-version" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradle-plugin-version-catalog-update-version" }

