/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.creation;

/**
 *
 * @author astrapi69
 */
public class NewBundleApplicationFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAddSupportedLocale;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnToDashboard;
	private javax.swing.JComboBox<String> cmbDefaultLocale;
	private javax.swing.JComboBox<String> cmbSupportedLocaleToAdd;
	private javax.swing.JLabel lbDefaultlLocale;
	private javax.swing.JLabel lblBundleName;
	private javax.swing.JLabel lblHeaderNewBundleApp;
	private javax.swing.JLabel lblSupportedLocales;
	private javax.swing.JLabel lblSupportedLocaleToAdd;
	private javax.swing.JScrollPane srcSupportedLocales;
	private javax.swing.JTable tblSupportedLocales;
	private javax.swing.JTextField txtBundleName;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form NewBundleApplicationFormPanel
	 */
	public NewBundleApplicationFormPanel()
	{
		initComponents();
	}

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnSaveActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSaveActionPerformed

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblHeaderNewBundleApp = new javax.swing.JLabel();
		lblBundleName = new javax.swing.JLabel();
		txtBundleName = new javax.swing.JTextField();
		btnSave = new javax.swing.JButton();
		btnToDashboard = new javax.swing.JButton();
		lbDefaultlLocale = new javax.swing.JLabel();
		cmbDefaultLocale = new javax.swing.JComboBox<>();
		lblSupportedLocales = new javax.swing.JLabel();
		btnAddSupportedLocale = new javax.swing.JButton();
		srcSupportedLocales = new javax.swing.JScrollPane();
		tblSupportedLocales = new javax.swing.JTable();
		cmbSupportedLocaleToAdd = new javax.swing.JComboBox<>();
		lblSupportedLocaleToAdd = new javax.swing.JLabel();

		lblHeaderNewBundleApp.setText("Create new bundle application");

		lblBundleName.setText("Application name");

		btnSave.setText("Create bundle application");
		btnSave.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnSaveActionPerformed(evt);
			}
		});

		btnToDashboard.setText("Return to Dashboard");

		lbDefaultlLocale.setText("Choose default Locale");

		cmbDefaultLocale.setModel(new javax.swing.DefaultComboBoxModel<>(
			new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblSupportedLocales.setText("Supported Locales ");

		btnAddSupportedLocale.setText("Add supported Locale");

		tblSupportedLocales.setModel(new javax.swing.table.DefaultTableModel(
			new Object[][] { { null, null }, { null, null }, { null, null } },
			new String[] { "Locale", "Action" }));
		srcSupportedLocales.setViewportView(tblSupportedLocales);

		cmbSupportedLocaleToAdd.setModel(new javax.swing.DefaultComboBoxModel<>(
			new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblSupportedLocaleToAdd.setText("Select supported Locale to add");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(34, 34, 34).addGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
				.addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 222,
					javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblHeaderNewBundleApp, javax.swing.GroupLayout.PREFERRED_SIZE,
						265, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220,
						Short.MAX_VALUE)
					.addComponent(btnToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(lbDefaultlLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblSupportedLocaleToAdd,
							javax.swing.GroupLayout.PREFERRED_SIZE, 200,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(cmbSupportedLocaleToAdd,
								javax.swing.GroupLayout.PREFERRED_SIZE, 286,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(btnAddSupportedLocale,
								javax.swing.GroupLayout.PREFERRED_SIZE, 174,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(cmbDefaultLocale, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
							Short.MAX_VALUE)))
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(lblSupportedLocales, javax.swing.GroupLayout.PREFERRED_SIZE,
							200, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblBundleName, javax.swing.GroupLayout.Alignment.LEADING,
							javax.swing.GroupLayout.PREFERRED_SIZE, 200,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(txtBundleName, javax.swing.GroupLayout.PREFERRED_SIZE, 460,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(
							srcSupportedLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 466,
							javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap(95, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(40, 40, 40)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblHeaderNewBundleApp, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(btnToDashboard))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(txtBundleName, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(lblBundleName))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(cmbDefaultLocale, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(lbDefaultlLocale))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblSupportedLocaleToAdd)
					.addComponent(cmbSupportedLocaleToAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(btnAddSupportedLocale))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(srcSupportedLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(lblSupportedLocales))
				.addGap(18, 18, 18).addComponent(btnSave).addContainerGap(58, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents
}
