/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.creation;

/**
 *
 * @author astrapi69
 */
public class NewBundleNameFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCreateNewLocale;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnToDashboard;
	private javax.swing.JComboBox<String> cmbLocale;
	private javax.swing.JLabel lblBasename;
	private javax.swing.JLabel lblHeaderNewBundleName;
	private javax.swing.JLabel lblLocale;
	private javax.swing.JTextField txtBasename;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form NewBundleNamePanel
	 */
	public NewBundleNameFormPanel()
	{
		initComponents();
	}

	private void btnCreateNewLocaleActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnCreateNewLocaleActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnCreateNewLocaleActionPerformed

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnSaveActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSaveActionPerformed

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblLocale = new javax.swing.JLabel();
		cmbLocale = new javax.swing.JComboBox<>();
		lblBasename = new javax.swing.JLabel();
		txtBasename = new javax.swing.JTextField();
		btnSave = new javax.swing.JButton();
		lblHeaderNewBundleName = new javax.swing.JLabel();
		btnCreateNewLocale = new javax.swing.JButton();
		btnToDashboard = new javax.swing.JButton();

		lblLocale.setText("Choose Locale");

		cmbLocale.setModel(new javax.swing.DefaultComboBoxModel<>(
			new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblBasename.setText("Basename");

		txtBasename.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtBasenameActionPerformed(evt);
			}
		});

		btnSave.setText("Save entry");
		btnSave.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnSaveActionPerformed(evt);
			}
		});

		lblHeaderNewBundleName.setText("Create new Bundle name");

		btnCreateNewLocale.setText("Create new custom locale");
		btnCreateNewLocale.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnCreateNewLocaleActionPerformed(evt);
			}
		});

		btnToDashboard.setText("Return to Dashboard");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(40, 40, 40).addGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblBasename, javax.swing.GroupLayout.PREFERRED_SIZE,
						140, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18).addComponent(txtBasename,
						javax.swing.GroupLayout.PREFERRED_SIZE, 562,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(387, 387, 387).addComponent(
							btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 175,
							javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addComponent(cmbLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(btnCreateNewLocale,
								javax.swing.GroupLayout.PREFERRED_SIZE, 220,
								javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addGroup(layout.createSequentialGroup()
					.addComponent(lblHeaderNewBundleName, javax.swing.GroupLayout.PREFERRED_SIZE,
						300, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(btnToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
						javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(40, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblHeaderNewBundleName, javax.swing.GroupLayout.PREFERRED_SIZE,
						35, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(btnToDashboard))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblBasename).addComponent(txtBasename,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblLocale)
					.addComponent(cmbLocale, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addComponent(btnCreateNewLocale))
				.addGap(18, 18, 18).addComponent(btnSave).addContainerGap(37, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void txtBasenameActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtBasenameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtBasenameActionPerformed
}
