/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.creation;

/**
 *
 * @author astrapi69
 */
public class NewCustomLocaleFormPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSave;

	private javax.swing.JLabel lblCountry;

	private javax.swing.JLabel lblHeaderNewLocale;

	private javax.swing.JLabel lblLanguage;


	private javax.swing.JLabel lblVariant;
	private javax.swing.JTextField txtCountry;
	private javax.swing.JTextField txtLanguage;
	private javax.swing.JTextField txtVariant;
	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form NewCustomLocaleFormPanel
	 */
	public NewCustomLocaleFormPanel()
	{
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblHeaderNewLocale = new javax.swing.JLabel();
		lblLanguage = new javax.swing.JLabel();
		txtLanguage = new javax.swing.JTextField();
		lblCountry = new javax.swing.JLabel();
		txtCountry = new javax.swing.JTextField();
		lblVariant = new javax.swing.JLabel();
		txtVariant = new javax.swing.JTextField();
		btnSave = new javax.swing.JButton();

		lblHeaderNewLocale.setText("Create new custom locale");

		lblLanguage.setText("Language");

		txtLanguage.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtLanguageActionPerformed(evt);
			}
		});

		lblCountry.setText("Country");

		txtCountry.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtCountryActionPerformed(evt);
			}
		});

		lblVariant.setText("Variant");

		btnSave.setText("Save locale");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(46, 46, 46)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
							.addGroup(layout.createSequentialGroup()
								.addComponent(lblVariant, javax.swing.GroupLayout.PREFERRED_SIZE,
									120, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtVariant, javax.swing.GroupLayout.PREFERRED_SIZE,
									540, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(layout.createSequentialGroup()
								.addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE,
									120, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE,
									540, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addComponent(lblHeaderNewLocale,
								javax.swing.GroupLayout.PREFERRED_SIZE, 700,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGroup(layout.createSequentialGroup()
								.addComponent(lblLanguage, javax.swing.GroupLayout.PREFERRED_SIZE,
									120, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
									javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE,
									540, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addContainerGap(54, Short.MAX_VALUE)));
		layout
			.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
					.addComponent(lblHeaderNewLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblLanguage).addComponent(txtLanguage,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblCountry).addComponent(txtCountry,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblVariant).addComponent(txtVariant,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(18, 18, 18).addComponent(btnSave)
					.addContainerGap(28, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents
	private void txtCountryActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtCountryActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtCountryActionPerformed
	private void txtLanguageActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtLanguageActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtLanguageActionPerformed
}
