/*
 * Copyright 2017 Alpha Ro Group UG (haftungsbeschrängt).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.alpharogroup.bundle.app.panels.signin;

/**
 *
 * @author astrapi69
 */
public class SignInPanel extends javax.swing.JPanel
{

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSignin;

	private javax.swing.JLabel lblHeaderSignin;

	private javax.swing.JLabel lblPw;

	private javax.swing.JLabel lblUsername;


	private javax.swing.JTextField txtPw;
	private javax.swing.JTextField txtUsername;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form SignInPanel
	 */
	public SignInPanel()
	{
		initComponents();
	}

	private void btnSigninActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_btnSigninActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSigninActionPerformed

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		lblHeaderSignin = new javax.swing.JLabel();
		lblUsername = new javax.swing.JLabel();
		txtUsername = new javax.swing.JTextField();
		lblPw = new javax.swing.JLabel();
		txtPw = new javax.swing.JTextField();
		btnSignin = new javax.swing.JButton();

		lblHeaderSignin.setText("User sign in");

		lblUsername.setText("User name");

		lblPw.setText("Password");

		txtPw.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				txtPwActionPerformed(evt);
			}
		});

		btnSignin.setText("Sign in");
		btnSignin.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				btnSigninActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addGap(59, 59, 59)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
						javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblPw, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 540,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 540,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(lblHeaderSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 670,
							javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(69, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup().addContainerGap()
				.addComponent(lblHeaderSignin, javax.swing.GroupLayout.DEFAULT_SIZE,
					javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblUsername).addComponent(txtUsername,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(lblPw).addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(btnSignin).addGap(34, 34, 34)));
	}// </editor-fold>//GEN-END:initComponents

	private void txtPwActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_txtPwActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtPwActionPerformed
}
